version: '3.8'

services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.mage
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
  db:
    image: postgres:16.6
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - backend:/var/lib/postgresql/data
volumes:
  backend: